# Batch variant scoring

In this notebook, we demonstrate how to score many variants using AlphaGenome.

To prepare numerous variants for scoring, provide the following information as
columns in a tab-separated Variant Call Format (VCF) file: - `variant_id`: A
unique identifier for each variant. - `CHROM`: Chromosome, specified as a string
beginning with 'chr' (e.g., 'chr1'). - `POS`: Integer representing the base pair
position (1-based; build hg38 (human) or mm10 (mouse) - see
[FAQ](https://www.alphagenomedocs.com/faqs.html#how-do-i-define-a-variant)). -
`REF`: The reference nucleotide sequence at the specified position. - `ALT`: The
alternate nucleotide sequence at the specified position.

``` {tip}
Open this tutorial in Google Colab for interactive viewing.
```

In [1]:
# @title Install AlphaGenome

# @markdown Run this cell to install AlphaGenome.
from IPython.display import clear_output
! pip install alphagenome
clear_output()

In [2]:
# @title Setup and imports.

from io import StringIO
from alphagenome import colab_utils
from alphagenome.data import genome
from alphagenome.models import dna_client, variant_scorers
from google.colab import data_table, files
import pandas as pd
from tqdm import tqdm

data_table.enable_dataframe_formatter()

# Load the model.
dna_model = dna_client.create(colab_utils.get_api_key())

In [5]:
# @title Score batch of variants.

# Load VCF file containing variants.
vcf_file = '/content/AQP4_all_variants_MAF.vcf'  # @param

# We provide an example list of variants to illustrate.
#vcf_file = """variant_id\tCHROM\tPOS\tREF\tALT
#chr3_58394738_A_T_b38\tchr3\t58394738\tA\tT
#chr8_28520_G_C_b38\tchr8\t28520\tG\tC
#chr16_636337_G_A_b38\tchr16\t636337\tG\tA
#chr16_1135446_G_T_b38\tchr16\t1135446\tG\tT
#"""

vcf_full = pd.read_csv(vcf_file, sep='\t')

required_columns = ['variant_id', 'CHROM', 'POS', 'REF', 'ALT']
for column in required_columns:
  if column not in vcf_full.columns:
    raise ValueError(f'VCF file is missing required column: {column}.')

organism = 'human'  # @param ["human", "mouse"] {type:"string"}

# @markdown Specify length of sequence around variants to predict:
sequence_length = '1MB'  # @param ["16KB", "100KB", "500KB", "1MB"] { type:"string" }
sequence_length = dna_client.SUPPORTED_SEQUENCE_LENGTHS[
    f'SEQUENCE_LENGTH_{sequence_length}'
]

# @markdown Specify which scorers to use to score your variants:
score_rna_seq = True  # @param { type: "boolean"}
score_cage = True  # @param { type: "boolean" }
score_procap = True  # @param { type: "boolean" }
score_atac = True  # @param { type: "boolean" }
score_dnase = True  # @param { type: "boolean" }
score_chip_histone = True  # @param { type: "boolean" }
score_chip_tf = True  # @param { type: "boolean" }
score_polyadenylation = True  # @param { type: "boolean" }
score_splice_sites = True  # @param { type: "boolean" }
score_splice_site_usage = True  # @param { type: "boolean" }
score_splice_junctions = True  # @param { type: "boolean" }

# @markdown Other settings:
download_predictions = True  # @param { type: "boolean" }

# Parse organism specification.
organism_map = {
    'human': dna_client.Organism.HOMO_SAPIENS,
    'mouse': dna_client.Organism.MUS_MUSCULUS,
}
organism = organism_map[organism]

# Parse scorer specification.
scorer_selections = {
    'rna_seq': score_rna_seq,
    'cage': score_cage,
    'procap': score_procap,
    'atac': score_atac,
    'dnase': score_dnase,
    'chip_histone': score_chip_histone,
    'chip_tf': score_chip_tf,
    'polyadenylation': score_polyadenylation,
    'splice_sites': score_splice_sites,
    'splice_site_usage': score_splice_site_usage,
    'splice_junctions': score_splice_junctions,
}

all_scorers = variant_scorers.RECOMMENDED_VARIANT_SCORERS
selected_scorers = [
    all_scorers[key]
    for key in all_scorers
    if scorer_selections.get(key.lower(), False)
]

# Remove any scorers or output types that are not supported for the chosen organism.
unsupported_scorers = [
    scorer
    for scorer in selected_scorers
    if (
        organism.value
        not in variant_scorers.SUPPORTED_ORGANISMS[scorer.base_variant_scorer]
    )
    | (
        (scorer.requested_output == dna_client.OutputType.PROCAP)
        & (organism == dna_client.Organism.MUS_MUSCULUS)
    )
]
if len(unsupported_scorers) > 0:
  print(
      f'Excluding {unsupported_scorers} scorers as they are not supported for'
      f' {organism}.'
  )
  for unsupported_scorer in unsupported_scorers:
    selected_scorers.remove(unsupported_scorer)



#if 'df_scores' not in locals() and 'df_scores' not in globals():
df_scores = pd.DataFrame()

chunk_size = 100  # number of rows per chunk
print(len(vcf_full)/chunk_size, "chunks")

for i in range(0, len(vcf_full), chunk_size):
  print("Processing chunk", i/chunk_size)
  vcf = vcf_full.iloc[i:i + chunk_size,:]

  # Score variants in the VCF file.
  results = []

  for i, vcf_row in tqdm(vcf.iterrows(), total=len(vcf)):
    variant = genome.Variant(
       chromosome=str(vcf_row.CHROM),
       position=int(vcf_row.POS),
       reference_bases=vcf_row.REF,
       alternate_bases=vcf_row.ALT,
       name=vcf_row.variant_id,
    )
    interval = variant.reference_interval.resize(sequence_length)

    variant_scores = dna_model.score_variant(
        interval=interval,
       variant=variant,
       variant_scorers=selected_scorers,
        organism=organism,
   )
    results.append(variant_scores)

  df_scores_part = variant_scorers.tidy_scores(results)
  df_scores_part = df_scores_part.loc[(df_scores_part['quantile_score'] > 0.90) | (df_scores_part['quantile_score'] < -0.90)]
  df_scores_part = df_scores_part.loc[(df_scores_part['biosample_name'] == 'astrocyte') | (df_scores_part['biosample_name'] == 'brain')]
  df_scores = pd.concat([df_scores, df_scores_part], ignore_index=True)

if download_predictions:
  df_scores.to_csv('variant_scores.csv', index=False)
  files.download('variant_scores.csv')

df_scores

0.36 chunks
Processing chunk 0.0

100%|██████████| 36/36 [00:47<00:00,  1.33s/it]

Warning: Total number of columns (25) exceeds max_columns (20). Falling back to pandas display.

,variant_id,scored_interval,gene_id,gene_name,gene_type,gene_strand,junction_Start,junction_End,output_type,variant_scorer,...,biosample_type,biosample_life_stage,data_source,endedness,genetically_modified,transcription_factor,histone_mark,gtex_tissue,raw_score,quantile_score
0,chr18:26861589:G>A,chr18:26337301-27385877:.,None,None,None,None,None,None,CHIP_HISTONE,CenterMaskScorer(requested_output=CHIP_HISTONE...,...,tissue,embryonic,encode,single,False,NaN,H3K4me3,NaN,-0.020830,-0.923901
1,chr18:26861589:G>A,chr18:26337301-27385877:.,ENSG00000266184,ENSG00000266184,processed_pseudogene,-,None,None,RNA_SEQ,GeneMaskLFCScorer(requested_output=RNA_SEQ),...,tissue,adult,encode,paired,False,NaN,NaN,,-0.003205,-0.905090
2,chr18:26855354:G>A,chr18:26331066-27379642:.,None,None,None,None,None,None,CAGE,"CenterMaskScorer(requested_output=CAGE, width=...",...,tissue,NaN,fantom,NaN,NaN,NaN,NaN,NaN,-0.044091,-0.911155
3,chr18:26855354:G>A,chr18:26331066-27379642:.,ENSG00000266184,ENSG00000266184,processed_pseudogene,-,None,None,RNA_SEQ,GeneMaskLFCScorer(requested_output=RNA_SEQ),...,tissue,adult,encode,paired,False,NaN,NaN,,0.003167,0.905090
4,chr18:26855354:G>A,chr18:26331066-27379642:.,ENSG00000171885,AQP4,protein_coding,-,None,None,RNA_SEQ,PolyadenylationScorer(),...,primary_cell,unknown,encode,paired,False,NaN,NaN,,0.031858,0.985213
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,chr18:26866755:T>C,chr18:26342467-27391043:.,None,None,None,None,None,None,CHIP_HISTONE,CenterMaskScorer(requested_output=CHIP_HISTONE...,...,tissue,embryonic,encode,single,False,NaN,H3K4me3,NaN,0.023496,0.933411
262,chr18:26866755:T>C,chr18:26342467-27391043:.,None,None,None,None,None,None,CAGE,"CenterMaskScorer(requested_output=CAGE, width=...",...,tissue,NaN,fantom,NaN,NaN,NaN,NaN,NaN,0.086881,0.970426
263,chr18:26855248:G>T,chr18:26330960-27379536:.,ENSG00000171885,AQP4,protein_coding,-,None,None,RNA_SEQ,GeneMaskLFCScorer(requested_output=RNA_SEQ),...,tissue,adult,encode,paired,False,NaN,NaN,,-0.004270,-0.949106
264,chr18:26855248:G>T,chr18:26330960-27379536:.,ENSG00000265369,PCAT18,lncRNA,-,None,None,RNA_SEQ,GeneMaskLFCScorer(requested_output=RNA_SEQ),...,tissue,adult,encode,paired,False,NaN,NaN,,-0.004017,-0.941769
265,chr18:26855248:G>T,chr18:26330960-27379536:.,ENSG00000171885,AQP4,protein_coding,-,26861295,26865657,SPLICE_JUNCTIONS,SpliceJunctionScorer(),...,tissue,adult,encode,NaN,NaN,NaN,NaN,,0.036011,0.957496

In [10]:
df_scores = pd.read_csv('variant_scores_MAF.csv')

Note that the resulting output dataframe could be quite large, especially if you
use many scorers for scoring. Very large dataframes can't be filtered
interactively, but you can interact with them using the standard `pandas`
commands:

In [15]:
# Examine just the effects of the variants on T-cells.
#columns = [c for c in df_scores.columns if c != 'ontology_curie']
#df_scores[(df_scores['ontology_curie'] == 'CL:0000127')][columns]

df_scores = df_scores.loc[(df_scores['quantile_score'] > 0.95) | (df_scores['quantile_score'] < -0.95)]
df_scores = df_scores.loc[df_scores['biosample_name'] == 'astrocyte']
#df_scores = df_scores.loc[df_scores['biosample_name'] == 'brain']
df_scores['SNP'] = df_scores['variant_id']
df_scores['Main MAF Population'] = df_scores['variant_id']

df_scores = df_scores.replace({"SNP":
    {'chr18:26855354:G>A': 'rs114892361',
     'chr18:26860169:C>A': 'rs114622499',
     'chr18:26863064:C>G': 'rs112481323',
     'chr18:26863655:A>G': 'rs111931765',
     'chr18:26863111:G>A': 'rs77905661',
     'chr18:26857815:G>A': 'rs73945980',
     'chr18:26857134:G>A': 'rs73945979',
     'chr18:26854566:C>G': 'rs73945976',
     'chr18:26863088:G>A': 'rs72878776',
     'chr18:26862263:C>T': 'rs72557968',
     'chr18:26864186:T>C': 'rs12968026',
     'chr18:26865469:T>C': 'rs3875089',
     'chr18:26859108:A>G': 'rs335931',
     'chr18:26864250:G>A': 'rs162009',
     'chr18:26867822:G>A': 'rs162005',
     }})

df_scores = df_scores.replace({"Main MAF Population":
    {'chr18:26855354:G>A': 'African',
     'chr18:26860169:C>A': 'African',
     'chr18:26863064:C>G': 'African',
     'chr18:26863655:A>G': 'African',
     'chr18:26863111:G>A': 'European, African',
     'chr18:26857815:G>A': 'African',
     'chr18:26857134:G>A': 'African',
     'chr18:26854566:C>G': 'African, Latin American 1',
     'chr18:26863088:G>A': 'European',
     'chr18:26862263:C>T': 'South Asian',
     'chr18:26864186:T>C': 'European',
     'chr18:26865469:T>C': 'European, African, Latin American 1, South Asian',
     'chr18:26859108:A>G': 'European, Asian, Latin American',
     'chr18:26864250:G>A': 'European, African, Latin American, Asian',
     'chr18:26867822:G>A': 'European, African, Latin American, Asian (ALT > REF)',
     }})

cols_of_interest = ['variant_id','SNP','gene_name','gene_type','output_type','variant_scorer','raw_score','quantile_score','junction_Start',
                    'junction_End','transcription_factor','histone_mark','ontology_curie','biosample_name', 'Main MAF Population']
df_scores[cols_of_interest]
#df_scores

,variant_id,SNP,gene_name,gene_type,output_type,variant_scorer,raw_score,quantile_score,junction_Start,junction_End,transcription_factor,histone_mark,ontology_curie,biosample_name,Main MAF Population
4,chr18:26855354:G>A,rs114892361,AQP4,protein_coding,RNA_SEQ,PolyadenylationScorer(),0.031858,0.985213,NaN,NaN,NaN,NaN,CL:0000127,astrocyte,African
6,chr18:26860169:C>A,rs114622499,AQP4,protein_coding,RNA_SEQ,GeneMaskLFCScorer(requested_output=RNA_SEQ),-0.003705,-0.962893,NaN,NaN,NaN,NaN,CL:0000127,astrocyte,African
14,chr18:26863064:C>G,rs112481323,NaN,NaN,CHIP_HISTONE,CenterMaskScorer(requested_output=CHIP_HISTONE...,0.045665,0.967613,NaN,NaN,NaN,H3K27me3,CL:0000127,astrocyte,African
20,chr18:26863064:C>G,rs112481323,AQP4,protein_coding,RNA_SEQ,GeneMaskLFCScorer(requested_output=RNA_SEQ),-0.006757,-0.993767,NaN,NaN,NaN,NaN,CL:0000127,astrocyte,African
23,chr18:26863064:C>G,rs112481323,AQP4,protein_coding,SPLICE_JUNCTIONS,SpliceJunctionScorer(),0.047485,0.979689,26862596.0,26862961.0,NaN,NaN,CL:0000127,astrocyte,African
31,chr18:26863655:A>G,rs111931765,NaN,NaN,CHIP_HISTONE,CenterMaskScorer(requested_output=CHIP_HISTONE...,0.038219,0.961175,NaN,NaN,NaN,H2AFZ,CL:0000127,astrocyte,African
32,chr18:26863655:A>G,rs111931765,NaN,NaN,CHIP_HISTONE,CenterMaskScorer(requested_output=CHIP_HISTONE...,-0.029097,-0.951345,NaN,NaN,NaN,H3K27me3,CL:0000127,astrocyte,African
33,chr18:26863655:A>G,rs111931765,NaN,NaN,CHIP_HISTONE,CenterMaskScorer(requested_output=CHIP_HISTONE...,0.060750,0.950237,NaN,NaN,NaN,H3K4me2,CL:0000127,astrocyte,African
34,chr18:26863655:A>G,rs111931765,NaN,NaN,CHIP_HISTONE,CenterMaskScorer(requested_output=CHIP_HISTONE...,0.051119,0.972998,NaN,NaN,NaN,H3K4me3,CL:0000127,astrocyte,African
35,chr18:26863655:A>G,rs111931765,NaN,NaN,CHIP_HISTONE,CenterMaskScorer(requested_output=CHIP_HISTONE...,0.039170,0.955539,NaN,NaN,NaN,H3K9ac,CL:0000127,astrocyte,African
41,chr18:26863655:A>G,rs111931765,AQP4,protein_coding,RNA_SEQ,GeneMaskLFCScorer(requested_output=RNA_SEQ),0.013076,0.998918,NaN,NaN,NaN,NaN,CL:0000127,astrocyte,African
45,chr18:26863655:A>G,rs111931765,AQP4,protein_coding,SPLICE_JUNCTIONS,SpliceJunctionScorer(),0.034607,0.969552,26861295.0,26863656.0,NaN,NaN,CL:0000127,astrocyte,African
46,chr18:26863655:A>G,rs111931765,AQP4,protein_coding,SPLICE_JUNCTIONS,SpliceJunctionScorer(),0.026703,0.951491,26862839.0,26863656.0,NaN,NaN,CL:0000127,astrocyte,African
47,chr18:26863655:A>G,rs111931765,AQP4,protein_coding,SPLICE_JUNCTIONS,SpliceJunctionScorer(),0.057800,0.983806,26862473.0,26863656.0,NaN,NaN,CL:0000127,astrocyte,African
48,chr18:26863655:A>G,rs111931765,AQP4,protein_coding,SPLICE_JUNCTIONS,SpliceJunctionScorer(),0.034454,0.969552,26856419.0,26863656.0,NaN,NaN,CL:0000127,astrocyte,African
49,chr18:26863655:A>G,rs111931765,AQP4,protein_coding,SPLICE_JUNCTIONS,SpliceJunctionScorer(),0.056702,0.983435,26856489.0,26863656.0,NaN,NaN,CL:0000127,astrocyte,African
50,chr18:26863655:A>G,rs111931765,AQP4,protein_coding,SPLICE_JUNCTIONS,SpliceJunctionScorer(),0.051178,0.981447,26860852.0,26863656.0,NaN,NaN,CL:0000127,astrocyte,African
51,chr18:26863655:A>G,rs111931765,AQP4,protein_coding,SPLICE_JUNCTIONS,SpliceJunctionScorer(),0.053223,0.982268,26862592.0,26863656.0,NaN,NaN,CL:0000127,astrocyte,African
62,chr18:26863111:G>A,rs77905661,NaN,NaN,CHIP_HISTONE,CenterMaskScorer(requested_output=CHIP_HISTONE...,0.033683,0.952428,NaN,NaN,NaN,H2AFZ,CL:0000127,astrocyte,"European, African"
65,chr18:26863111:G>A,rs77905661,NaN,NaN,CHIP_HISTONE,CenterMaskScorer(requested_output=CHIP_HISTONE...,0.049202,0.971741,NaN,NaN,NaN,H3K4me3,CL:0000127,astrocyte,"European, African"
66,chr18:26863111:G>A,rs77905661,NaN,NaN,CHIP_HISTONE,CenterMaskScorer(requested_output=CHIP_HISTONE...,0.046980,0.966109,NaN,NaN,NaN,H3K9ac,CL:0000127,astrocyte,"European, African"
70,chr18:26863111:G>A,rs77905661,AQP4,protein_coding,RNA_SEQ,GeneMaskLFCScorer(requested_output=RNA_SEQ),0.008791,0.997402,NaN,NaN,NaN,NaN,CL:0000127,astrocyte,"European, African"
84,chr18:26857815:G>A,rs73945980,NaN,NaN,CHIP_TF,"CenterMaskScorer(requested_output=CHIP_TF, wid...",-0.059560,-0.962893,NaN,NaN,EZH2,NaN,CL:0000127,astrocyte,African
91,chr18:26857134:G>A,rs73945979,ENSG00000277534,lncRNA,RNA_SEQ,GeneMaskLFCScorer(requested_output=RNA_SEQ),-0.003432,-0.955539,NaN,NaN,NaN,NaN,CL:0000127,astrocyte,African
96,chr18:26854566:C>G,rs73945976,NaN,NaN,DNASE,"CenterMaskScorer(requested_output=DNASE, width...",0.160037,0.959379,NaN,NaN,NaN,NaN,CL:0000127,astrocyte,"African, Latin American 1"
98,chr18:26854566:C>G,rs73945976,NaN,NaN,CHIP_HISTONE,CenterMaskScorer(requested_output=CHIP_HISTONE...,0.034183,0.953488,NaN,NaN,NaN,H2AFZ,CL:0000127,astrocyte,"African, Latin American 1"
99,chr18:26854566:C>G,rs73945976,NaN,NaN,CHIP_HISTONE,CenterMaskScorer(requested_output=CHIP_HISTONE...,0.069187,0.969746,NaN,NaN,NaN,H3K27ac,CL:0000127,astrocyte,"African, Latin American 1"
100,chr18:26854566:C>G,rs73945976,NaN,NaN,CHIP_HISTONE,CenterMaskScorer(requested_output=CHIP_HISTONE...,-0.032495,-0.959379,NaN,NaN,NaN,H3K27me3,CL:0000127,astrocyte,"African, Latin American 1"
101,chr18:26854566:C>G,rs73945976,NaN,NaN,CHIP_HISTONE,CenterMaskScorer(requested_output=CHIP_HISTONE...,0.135019,0.985426,NaN,NaN,NaN,H3K4me1,CL:0000127,astrocyte,"African, Latin American 1"
102,chr18:26854566:C>G,rs73945976,NaN,NaN,CHIP_HISTONE,CenterMaskScorer(requested_output=CHIP_HISTONE...,0.159089,0.986394,NaN,NaN,NaN,H3K4me2,CL:0000127,astrocyte,"African, Latin American 1"
103,chr18:26854566:C>G,rs73945976,NaN,NaN,CHIP_HISTONE,CenterMaskScorer(requested_output=CHIP_HISTONE...,0.039157,0.960287,NaN,NaN,NaN,H3K4me3,CL:0000127,astrocyte,"African, Latin American 1"
108,chr18:26854566:C>G,rs73945976,AQP4,protein_coding,RNA_SEQ,GeneMaskLFCScorer(requested_output=RNA_SEQ),0.007580,0.995881,NaN,NaN,NaN,NaN,CL:0000127,astrocyte,"African, Latin American 1"
114,chr18:26854566:C>G,rs73945976,AQP4,protein_coding,RNA_SEQ,PolyadenylationScorer(),0.021613,0.965955,NaN,NaN,NaN,NaN,CL:0000127,astrocyte,"African, Latin American 1"
134,chr18:26863088:G>A,rs72878776,AQP4,protein_coding,RNA_SEQ,GeneMaskLFCScorer(requested_output=RNA_SEQ),0.004026,0.970426,NaN,NaN,NaN,NaN,CL:0000127,astrocyte,European
147,chr18:26862263:C>T,rs72557968,AQP4,protein_coding,RNA_SEQ,GeneMaskLFCScorer(requested_output=RNA_SEQ),-0.004803,-0.981678,NaN,NaN,NaN,NaN,CL:0000127,astrocyte,South Asian
164,chr18:26864186:T>C,rs12968026,NaN,NaN,DNASE,"CenterMaskScorer(requested_output=DNASE, width...",0.208763,0.971741,NaN,NaN,NaN,NaN,CL:0000127,astrocyte,European
165,chr18:26864186:T>C,rs12968026,NaN,NaN,CHIP_HISTONE,CenterMaskScorer(requested_output=CHIP_HISTONE...,0.058625,0.962893,NaN,NaN,NaN,H3K27ac,CL:0000127,astrocyte,European
169,chr18:26864186:T>C,rs12968026,AQP4,protein_coding,RNA_SEQ,GeneMaskLFCScorer(requested_output=RNA_SEQ),0.007852,0.996329,NaN,NaN,NaN,NaN,CL:0000127,astrocyte,European
184,chr18:26865469:T>C,rs3875089,AQP4,protein_coding,RNA_SEQ,GeneMaskLFCScorer(requested_output=RNA_SEQ),0.013506,0.998990,NaN,NaN,NaN,NaN,CL:0000127,astrocyte,"European, African, Latin American 1, South Asian"
217,chr18:26859108:A>G,rs335931,AQP4,protein_coding,RNA_SEQ,PolyadenylationScorer(),0.022076,0.967440,NaN,NaN,NaN,NaN,CL:0000127,astrocyte,"European, Asian, Latin American"
222,chr18:26864250:G>A,rs162009,NaN,NaN,DNASE,"CenterMaskScorer(requested_output=DNASE, width...",-0.269130,-0.981678,NaN,NaN,NaN,NaN,CL:0000127,astrocyte,"European, African, Latin American, Asian"
227,chr18:26864250:G>A,rs162009,NaN,NaN,CHIP_HISTONE,CenterMaskScorer(requested_output=CHIP_HISTONE...,-0.079524,-0.975349,NaN,NaN,NaN,H3K27ac,CL:0000127,astrocyte,"European, African, Latin American, Asian"
228,chr18:26864250:G>A,rs162009,NaN,NaN,CHIP_HISTONE,CenterMaskScorer(requested_output=CHIP_HISTONE...,-0.021107,-0.962893,NaN,NaN,NaN,H3K36me3,CL:0000127,astrocyte,"European, African, Latin American, Asian"
229,chr18:26864250:G>A,rs162009,NaN,NaN,CHIP_HISTONE,CenterMaskScorer(requested_output=CHIP_HISTONE...,-0.088614,-0.974781,NaN,NaN,NaN,H3K4me1,CL:0000127,astrocyte,"European, African, Latin American, Asian"
231,chr18:26864250:G>A,rs162009,NaN,NaN,CHIP_HISTONE,CenterMaskScorer(requested_output=CHIP_HISTONE...,-0.042198,-0.967613,NaN,NaN,NaN,H3K4me3,CL:0000127,astrocyte,"European, African, Latin American, Asian"
232,chr18:26864250:G>A,rs162009,NaN,NaN,CHIP_HISTONE,CenterMaskScorer(requested_output=CHIP_HISTONE...,-0.020772,-0.962893,NaN,NaN,NaN,H3K79me2,CL:0000127,astrocyte,"European, African, Latin American, Asian"
233,chr18:26864250:G>A,rs162009,NaN,NaN,CHIP_HISTONE,CenterMaskScorer(requested_output=CHIP_HISTONE...,-0.058095,-0.978501,NaN,NaN,NaN,H3K9ac,CL:0000127,astrocyte,"European, African, Latin American, Asian"
236,chr18:26864250:G>A,rs162009,CIAPIN1P,processed_pseudogene,RNA_SEQ,GeneMaskLFCScorer(requested_output=RNA_SEQ),0.003519,0.957501,NaN,NaN,NaN,NaN,CL:0000127,astrocyte,"European, African, Latin American, Asian"
239,chr18:26864250:G>A,rs162009,AQP4,protein_coding,RNA_SEQ,GeneMaskLFCScorer(requested_output=RNA_SEQ),-0.011767,-0.998540,NaN,NaN,NaN,NaN,CL:0000127,astrocyte,"European, African, Latin American, Asian"
242,chr18:26864250:G>A,rs162009,AQP4,protein_coding,SPLICE_JUNCTIONS,SpliceJunctionScorer(),0.026901,0.952545,26860852.0,26865657.0,NaN,NaN,CL:0000127,astrocyte,"European, African, Latin American, Asian"
259,chr18:26867822:G>A,rs162005,AQP4,protein_coding,RNA_SEQ,GeneMaskLFCScorer(requested_output=RNA_SEQ),0.004313,0.975904,NaN,NaN,NaN,NaN,CL:0000127,astrocyte,"European, African, Latin American, Asian (ALT ..."